### ISSUE TITLE
Modal 리렌더링 이슈 Refactor

### ISSUE THREAD

**Issue by OhWonJu** [prgrms-fe-devcourse/FEDC5_looky_heejin#147]
# 📌간단한 기능 설명
Context 내부의 상태가 변하는 경우 Provider 하위의 모든 컴포넌트의 리렌더링을 트리거함.
최초 직렬화 가능한 값만을 props 로 사용할 것을 권장하는 redux style 로 인해 ContextAPI 로 로직을 전환했으나, 해당 이슈로 인해
Zustand 를 사용하여 Modal 제어를 하는 형태로 리펙토리 예정

# 📄Todo
- [ ] Modal 제어를 ContexAPI 에서 Zustand 로 전환
- [ ] React Profiler 를 통해 두 방식의 성능 차이 측정
 
<br />
> 브랜치 명시 규칙
${issue번호}/${작업 내용 혹은 컴포넌트 내용}
ex) refactor/123-infinityScroll

**Comment by ksjdev** [comment]
@OhWonJu 행님 PR에 어제 슬랙에 올려주신 성능 측정 내용 같이 올려서 남겨주시면 좋을 것 같습니다!
