### ISSUE TITLE
[BUG] 스크롤 바가 생겨서 화면이 왼쪽으로 밀리는 현상

### ISSUE THREAD

**Issue by SoJuSo** [prgrms-fe-devcourse/FEDC5_looky_heejin#32]
## ❗설명
스크롤바가 생기는 경우 저희가 의도하지 않았는데도 화면 자체가 밀리는 현상이 발생하고 있습니다.
![스크롤바생겨서밀림](https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/assets/90549862/81668ffc-cef0-42f5-b24e-fe503c1f52b8)

## 🚀관련 기능, 사용자 멘션
전체 레이아웃, looky팀 전원

## 💡제안
음 스크롤바를 좀 더 깔끔하게 하는 방법이 없을까요? 전통적인 스크롤바가 아닌 floating 스크롤바 라던지...그런...
아니면 스크롤바가 생기더라도 위치를 고정해주도록 레이아웃을 다시 잡아줘야할 것 같습니다.

**Comment by OhWonJu** [comment]
지그재그도 보면 밀림현상은 어쩔수 없는것 같아보이네요

**Comment by SoJuSo** [comment]
원주님이 깔끔하게 해결해주셔서 이슈 닫겠습니다~
